["root","Row",{"padding":8,"itemMargin":8,"borderRadius":20,"clip":true,"justifyContent":"center","alignItems":"center","linearGradient":{"direction":"RightBottom","colors":[["#FFCBDDFE",0],["#FFF1F6FE",1]]}},["weatherZone","secondaryColumn"]]
["weatherZone","Column",{"width":138,"height":134,"padding":12,"itemMargin":4,"borderRadius":16,"backgroundColor":"#99FFFFFF"},["weatherContent","weatherButton"]]
["weatherLabel","Text",{"content":"上海天气","fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["weatherContent","Column",{"width":114,"layoutWeight":1,"itemMargin":2,"justifyContent":"center"},["weatherLabel","weatherReadout","weatherStatus"]]
["weatherReadout","Row",{"width":114,"height":42,"alignItems":"bottom","itemMargin":2},["weatherValue"]]
["weatherValue","Text",{"content":"{{ ${/data/weather/current/temperatureC} + '°C' }}","fontSize":20,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1,"width":114,"height":28}]
["weatherStatus","Text",{"content":{"path":"/data/weather/current/condition"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["weatherButton","Button",{"label":"查看天气","width":114,"height":36,"borderRadius":18,"backgroundColor":"#331F4799","fontColor":"#FF1F4799","fontSize":14,"fontWeight":400,"onClick":[{"call":"clickToDeeplink","args":{"intentName":"Weather_CityCode","uri":"{{ 'hww://www.huawei.com/totemweather?enterType=share&cityCode=' + ${/data/weather/location/cityCode} }}"}}]}]
["secondaryColumn","Column",{"width":138,"height":134,"itemMargin":4,"padding":12},["batteryZone","earphoneZone"]]
["batteryZone","Column",{"width":114,"padding":12,"itemMargin":2,"borderRadius":16,"backgroundColor":"#99FFFFFF","justifyContent":"center","layoutWeight":1},["batteryValue","batteryAux"]]
["batteryValue","Text",{"content":"{{ ${/data/phoneBattery/batterySOC} + '%' }}","width":114,"fontSize":14,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["batteryAux","Text",{"content":{"path":"/data/phoneBattery/chargingStatusDesc"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["earphoneZone","Row",{"width":114,"height":36,"padding":8,"itemMargin":8,"justifyContent":"start","alignItems":"center","onClick":[{"call":"clickToDeeplink","args":{"intentName":"Settings","bundleName":"com.huawei.hmos.settings","abilityName":"com.huawei.hmos.settings.MainAbility","uri":"bluetooth_entry"}}]},["earphoneText","earphoneIcon"]]
["earphoneText","Column",{"width":70,"itemMargin":2,"justifyContent":"center"},["earphoneValue","earphoneStatus"]]
["earphoneValue","Text",{"content":"耳机","width":70,"fontSize":14,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["earphoneStatus","Text",{"content":"未连接","width":70,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["earphoneIcon","Image",{"src":"resources/base/media/earphone_case_16644.svg","width":20,"height":20,"objectFit":"contain","fillColor":"#FF1F4799","flexShrink":0}]
["/data/weather/location/cityCode","101020100"]
["/data/weather/current/condition","多云"]
["/data/weather/current/temperatureC",29]
["/data/phoneBattery/batterySOC",68]
["/data/phoneBattery/chargingStatusDesc","未充电"]
