# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
from enum import StrEnum


class GenerationStatus(StrEnum):
    SUCCESS = "success"
    DEGRADED = "degraded"
    UNSUPPORTED = "unsupported"
    FAILED = "failed"


class ErrorCode(StrEnum):
    UNKNOWN_CAPABILITY = "UNKNOWN_CAPABILITY"
    ROM_VERSION_UNSUPPORTED = "ROM_VERSION_UNSUPPORTED"
    APP_VERSION_UNSUPPORTED = "APP_VERSION_UNSUPPORTED"
    PACKAGE_NOT_INSTALLED = "PACKAGE_NOT_INSTALLED"
    PACKAGE_VERSION_TOO_LOW = "PACKAGE_VERSION_TOO_LOW"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    INTENT_TARGET_NOT_FOUND = "INTENT_TARGET_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    PERMISSION_UNKNOWN = "PERMISSION_UNKNOWN"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    WRITE_RESULT_CONFLICT = "WRITE_RESULT_CONFLICT"
    NO_EFFECTIVE_CAPABILITY = "NO_EFFECTIVE_CAPABILITY"
    A2UI_GENERATION_FAILED = "A2UI_GENERATION_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    ARTIFACT_UPLOAD_FAILED = "ARTIFACT_UPLOAD_FAILED"
    TIMEOUT = "TIMEOUT"
