["root","Row",{"width":"matchParent","height":"matchParent","padding":8,"itemMargin":8,"borderRadius":20,"clip":true,"justifyContent":"center","alignItems":"center","linearGradient":{"direction":"RightBottom","colors":[["#FFCBDDFE",0],["#FFF1F6FE",1]]}},["phoneZone","earphoneZone"]]
["phoneZone","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#99FFFFFF"},["phoneContent"]]
["phoneContent","Column",{"width":114,"layoutWeight":1,"justifyContent":"center","alignItems":"start","itemMargin":4},["phoneLabel","phoneValue","phoneStatus"]]
["phoneLabel","Text",{"content":"手机电量","width":114,"fontSize":30,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["phoneValue","Text",{"content":{"path":"/data/phoneBattery/batterySOCText"},"width":114,"height":28,"fontSize":20,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["phoneStatus","Text",{"content":{"path":"/data/phoneBattery/chargingStatusDesc"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["earphoneZone","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#99FFFFFF"},["earphoneContent"]]
["earphoneContent","Column",{"width":114,"layoutWeight":1,"justifyContent":"center","alignItems":"start","itemMargin":4},["earphoneName","earphoneStatus","caseBattery"]]
["earphoneName","Text",{"content":{"path":"/data/earphone/earphoneName"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["earphoneStatus","Text",{"content":"{{ ${/data/earphone/isConnected} ? '已连接' : '未连接' }}","width":114,"height":26,"fontSize":18,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["caseBattery","Text",{"content":"{{ '充电盒 ' + ${/data/earphone/batteryLevel} + '%' }}","width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["/data/phoneBattery/batterySOCText","68%"]
["/data/phoneBattery/chargingStatusDesc","未充电"]
["/data/earphone/earphoneName","FreeBuds Pro"]
["/data/earphone/isConnected",true]
["/data/earphone/batteryLevel",80]
