["root","Row",{"width":"matchParent","height":"matchParent","padding":8,"itemMargin":8,"borderRadius":20,"clip":true,"alignItems":"center","linearGradient":{"direction":"RightBottom","colors":[["#FFCBDDFE",0],["#FFF1F6FE",1]]},"justifyContent":"center"},["weatherZone","batteryZone"]]
["weatherZone","Column",{"width":138,"height":134,"padding":12,"itemMargin":4,"borderRadius":16,"backgroundColor":"#99FFFFFF"},["weatherContent","weatherButton","new"]]
["weatherTitle","Text",{"content":"上海天气","width":114,"height":16,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["weatherContent","Column",{"width":114,"layoutWeight":1,"itemMargin":2,"justifyContent":"center"},["weatherTitle","weatherValue","weatherStatus"]]
["weatherValue","Text",{"content":"{{ ${/data/weather/current/temperatureC} + '°C' }}","width":114,"height":34,"fontSize":24,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["weatherStatus","Text",{"content":{"path":"/data/weather/current/condition"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["weatherButton","Button",{"label":"查看天气","width":114,"height":36,"borderRadius":18,"backgroundColor":"#331F4799","fontColor":"#FF1F4799","fontSize":14,"fontWeight":400,"onClick":[{"call":"clickToDeeplink","args":{"intentName":"Weather_CityCode","uri":"{{ 'hww://www.huawei.com/totemweather?enterType=share&cityCode=' + ${/data/weather/location/cityCode} }}"}}]}]
["batteryZone","Column",{"width":138,"height":134,"padding":12,"itemMargin":4,"borderRadius":16,"backgroundColor":"#99FFFFFF"},["batteryContent","batteryButton"]]
["batteryTitle","Text",{"content":"手机电量","width":114,"height":16,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["batteryContent","Column",{"width":114,"layoutWeight":1,"itemMargin":2,"justifyContent":"center"},["batteryTitle","batteryValue","batteryStatus"]]
["batteryValue","Text",{"content":"{{ ${/data/phoneBattery/batterySOC} + '%' }}","width":114,"height":28,"fontSize":20,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["batteryStatus","Text",{"content":{"path":"/data/phoneBattery/chargingStatusDesc"},"width":114,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["batteryButton","Button",{"label":"电池设置","width":114,"height":36,"borderRadius":18,"backgroundColor":"#331F4799","fontColor":"#FF1F4799","fontSize":14,"fontWeight":400,"onClick":[{"call":"clickToDeeplink","args":{"intentName":"Settings","bundleName":"com.huawei.hmos.settings","abilityName":"com.huawei.hmos.settings.MainAbility","uri":"battery"}}]}]
["/data/weather/location/cityCode","101020100"]
["/data/weather/current/condition","多云"]
["/data/weather/current/temperatureC",29]
["/data/phoneBattery/batterySOC",68]
["/data/phoneBattery/chargingStatusDesc","未充电"]
["new","Button",{"label":"打开","onClick":[{"call":"open","args":{}}]}]
