["root","Column",{"padding":12,"itemMargin":4},["value_row","metrics","action_area"]]
["value_row","Row",{"width":136},["steps","unit"]]
["steps","Text",{"content":{"path":"/data/healthSport/calorieText"},"fontSize":12,"fontWeight":700,"maxLines":1}]
["unit","Text",{"content":"步","fontSize":12,"fontWeight":500,"maxLines":1}]
["metrics","Row",{"width":136,"height":18,"itemMargin":4},["calorie","separator","heart_rate"]]
["calorie","Text",{"content":{"path":"/data/healthSport/calorieText"},"fontSize":12,"fontWeight":400,"maxLines":1}]
["separator","Text",{"content":"|","fontSize":12,"fontWeight":400,"maxLines":1}]
["heart_rate","Text",{"content":{"path":"/data/healthSport/heartRateText"},"fontSize":12,"fontWeight":400,"maxLines":1}]
["action_area","Column",{"width":136,"height":36,"alignItems":"center"},["action"]]
["action","Row",{"width":126,"height":36,"padding":8,"itemMargin":8,"justifyContent":"center","alignItems":"center","onClick":[{"call":"openMusic","args":{}}]},["icon","label"]]
["icon","Image",{"src":"resources/base/media/music_fill.svg","width":20,"height":20,"objectFit":"contain","fillColor":"#FF1F4799"}]
["label","Text",{"content":"打开歌单","fontSize":14,"fontWeight":400,"maxLines":1}]
["/data/healthSport/steps",2319]
["/data/healthSport/calorieText","260 千卡"]
["/data/healthSport/heartRateText","135次/分钟"]
