["root","Column",{"padding":8,"itemMargin":8},["one","two"]]
["one","Column",{"width":134,"height":63,"padding":12,"backgroundColor":"#11563D99","borderRadius":12,"justifyContent":"center"},["onetext"]]
["onetext","Text",{"content":{"path":"/data/countdown/countdownDays"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["two","Column",{"width":134,"height":63,"padding":12,"backgroundColor":"#11563D99","borderRadius":12,"justifyContent":"center"},["twotext"]]
["twotext","Text",{"content":{"path":"/data/other/status"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["/data/countdown/countdownDays",10]
["/data/other/status","状态"]
