["root","Row",{"padding":12,"itemMargin":10},["focus","aux"]]
["focus","Column",{"width":136,"height":126,"justifyContent":"center","alignItems":"center"},["main","new","new2","new3","new4"]]
["main","Text",{"content":{"path":"/data/healthSport/a"},"fontSize":20,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["aux","Column",{"width":130,"height":126,"itemMargin":8},["cell1","cell2"]]
["cell1","Column",{"width":130,"height":59,"padding":12,"borderRadius":12,"backgroundColor":"#11563D99","justifyContent":"center","alignItems":"start"},["sub1"]]
["cell2","Column",{"width":130,"height":59,"padding":12,"borderRadius":12,"backgroundColor":"#11563D99","justifyContent":"center","alignItems":"start"},["sub2"]]
["sub1","Text",{"content":{"path":"/data/healthSport/b"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["sub2","Text",{"content":{"path":"/data/healthSport/c"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["/data/healthSport/a",5000]
["/data/healthSport/b","距离 3km"]
["/data/healthSport/c","热量 120kcal"]
["/data/healthSport/d","今日"]
["new","Text",{"content":"辅助","fontSize":12,"fontWeight":400,"maxLines":1}]
["new2","Text",{"content":"辅助","fontSize":12,"fontWeight":400,"maxLines":1}]
["new3","Text",{"content":"辅助","fontSize":12,"fontWeight":400,"maxLines":1}]
["new4","Text",{"content":"辅助","fontSize":12,"fontWeight":400,"maxLines":1}]
