["root","Row",{"padding":8,"itemMargin":8},["left","right"]]
["left","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#11563D99"},["leftcontent"]]
["leftcontent","Column",{"layoutWeight":1,"justifyContent":"center"},["left0","left1","split"]]
["left0","Text",{"content":"{{ ${/data/weather/daily/0/weekday} + ${/data/weather/daily/0/temperature} }}","fontSize":12,"maxLines":1,"fontColor":"#FF563D99","fontWeight":400}]
["left1","Text",{"content":"{{ ${/data/weather/daily/1/weekday} + ${/data/weather/daily/1/temperature} }}","fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["right","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#11563D99"},["rightcontent"]]
["rightcontent","Column",{"layoutWeight":1,"justifyContent":"center"},["right0"]]
["right0","Text",{"content":{"path":"/data/other/x"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["/data/weather/x","甲"]
["/data/weather/y","乙"]
["/data/weather/z","丙"]
["/data/other/x","甲"]
["/data/other/y","乙"]
["/data/other/z","丙"]
["/data/weather/daily",[{"date":"10-08","weekday":"周四","temperature":"18℃"},{"date":"10-09","weekday":"周五","temperature":"20℃"}]]
["split","Text",{"content":{"path":"/data/weather/daily/0/weekday"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
