["root","Row",{"width":"matchParent","padding":12,"borderRadius":20,"clip":true,"itemMargin":10,"justifyContent":"center","alignItems":"center","linearGradient":{"direction":"RightBottom","colors":[["#FFCBDDFE",0],["#FFF1F6FE",1]]}},["focus","details"]]
["focus","Column",{"width":136,"height":126,"itemMargin":4,"justifyContent":"center","alignItems":"center"},["name","statusArea"]]
["name","Text",{"content":{"path":"/data/earphone/earphoneName"},"width":136,"fontSize":12,"fontWeight":400,"fontColor":"#991F4799","maxLines":1}]
["statusArea","Column",{"width":136,"layoutWeight":1,"justifyContent":"center","alignItems":"start"},["status"]]
["status","Text",{"content":"{{ ${/data/earphone/isConnected} ? '已连接' : '未连接' }}","width":136,"fontSize":18,"fontWeight":700,"fontColor":"#FF1F4799","maxLines":1}]
["details","Column",{"width":130,"height":126,"itemMargin":8},["batterySummary","settingsAction"]]
["batterySummary","Column",{"width":130,"height":59,"padding":{"left":12,"right":12,"top":6,"bottom":6},"borderRadius":12,"backgroundColor":"#99FFFFFF","itemMargin":2,"justifyContent":"center"},["leftBattery","rightBattery"]]
["leftBattery","Text",{"content":"{{ '左耳 ' + ${/data/earphone/leftBatteryLevel} + '%' }}","width":106,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["rightBattery","Text",{"content":"{{ '右耳 ' + ${/data/earphone/rightBatteryLevel} + '%' }}","width":106,"fontSize":12,"fontWeight":400,"fontColor":"#FF1F4799","maxLines":1}]
["settingsAction","Row",{"width":130,"height":59,"padding":{"left":12,"right":12},"borderRadius":12,"backgroundColor":"#99FFFFFF","justifyContent":"start","alignItems":"center"},["settingsLabel"]]
["settingsLabel","Text",{"content":"蓝牙设置","width":106,"fontSize":14,"fontWeight":500,"fontColor":"#FF1F4799","textAlign":"start","maxLines":1}]
["/data/earphone/isConnected",true]
["/data/earphone/earphoneName","FreeBuds Pro 3"]
["/data/earphone/leftBatteryLevel",76]
["/data/earphone/rightBatteryLevel",78]
