["root","Row",{"padding":8,"itemMargin":8},["left","right"]]
["left","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#11563D99"},["leftcontent"]]
["leftcontent","Column",{"layoutWeight":1,"justifyContent":"center"},["left0","left1","left2"]]
["left0","Text",{"content":"{{ '温度 ' + ${/data/weather/temperatureRangeText} }}","fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["left1","Text",{"content":{"path":"/data/weather/rainProbabilityPercent"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["left2","Text",{"content":"{{ '空气 ' + ${/data/weather/airQuality} }}","fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["right","Column",{"width":138,"height":134,"padding":12,"borderRadius":16,"backgroundColor":"#11563D99"},["rightcontent"]]
["rightcontent","Column",{"layoutWeight":1,"justifyContent":"center"},["right0"]]
["right0","Text",{"content":{"path":"/data/other/a"},"fontSize":12,"fontWeight":400,"maxLines":1,"fontColor":"#FF563D99"}]
["/data/weather/temperatureRangeText","18~26℃"]
["/data/weather/rainProbabilityPercent",20]
["/data/weather/airQuality","优"]
["/data/other/a","甲"]
["/data/other/b","乙"]
["/data/other/c","丙"]
