["root","Row",{"width":"matchParent","height":"matchParent","padding":12,"borderRadius":20,"clip":true,"itemMargin":10,"justifyContent":"center","alignItems":"center","linearGradient":{"direction":"RightBottom","colors":[["#FFDBCCFF",0],["#FFF6F2FF",1]]}},["hero","details"]]
["hero","Column",{"width":136,"height":126,"itemMargin":8,"alignItems":"center"},["reading","bar"]]
["reading","Column",{"width":136,"layoutWeight":1,"justifyContent":"center","alignItems":"center","itemMargin":4},["valueRow","label"]]
["valueRow","Row",{"width":136,"itemMargin":4,"justifyContent":"center","alignItems":"bottom"},["value","unit"]]
["value","Text",{"content":{"path":"/data/healthSport/sleepScore"},"fontWeight":700,"fontColor":"#FF563D99","maxLines":1}]
["label","Text",{"content":"睡眠得分 / 100分","width":136,"fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","textAlign":"center","maxLines":1}]
["bar","Progress",{"type":"linear","width":136,"height":8,"strokeWidth":8,"value":{"path":"/data/healthSport/sleepScore"},"total":100,"color":"#FF563D99","backgroundColor":"#33563D99"}]
["details","Column",{"width":130,"height":126,"itemMargin":8},["night","deep"]]
["unit","Text",{"content":"分","fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","padding":{"bottom":7},"maxLines":1}]
["night","Column",{"width":130,"height":59,"padding":10,"borderRadius":12,"backgroundColor":"#99FFFFFF","itemMargin":4,"justifyContent":"center"},["nightLabel","nightValue"]]
["nightLabel","Text",{"content":"夜间睡眠","width":110,"fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","maxLines":1}]
["nightValue","Text",{"content":{"path":"/data/healthSport/nightSleepDurationText"},"width":110,"fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","maxLines":1}]
["deep","Column",{"width":130,"height":59,"padding":10,"borderRadius":12,"backgroundColor":"#99FFFFFF","itemMargin":4,"justifyContent":"center"},["deepLabel","deepValue"]]
["deepLabel","Text",{"content":"深睡时长","width":110,"fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","maxLines":1}]
["deepValue","Text",{"content":{"path":"/data/healthSport/deepSleepDurationText"},"width":110,"fontSize":12,"fontWeight":400,"fontColor":"#FF563D99","maxLines":1}]
["/data/healthSport/sleepScore",82]
["/data/healthSport/nightSleepDurationText","7小时1分"]
["/data/healthSport/deepSleepDurationText","2小时15分"]
