export type GalleryCardSize = "2x2" | "2x4";

export type GalleryComponent = {
  id: string;
  name: string;
  category: "基础结构" | "共享组件" | "2×2 组件" | "2×4 组件";
  sizes: GalleryCardSize[];
  summary: string;
  usage: string;
  props: string[];
  size: GalleryCardSize;
  width: 150 | 300;
  height: 150;
  source: string;
};

export type GalleryGroup = {
  id: string;
  title: GalleryComponent["category"];
  description: string;
};

const BLUE = "#FF1F4799";
const BLUE_SOFT = "#331F4799";
const PURPLE = "#FF563D99";
const PURPLE_SOFT = "#33563D99";
const ORANGE = "#FF8C4B1C";
const ORANGE_SOFT = "#338C4B1C";
const WHITE_PANEL = "#99FFFFFF";

const action = (uri: string) => [{ call: "clickToDeeplink", args: { uri } }];
const dsl = (...rows: unknown[][]) => rows.map(row => JSON.stringify(row)).join("\n");

const squareRoot = (
  children: string[],
  options: Record<string, unknown> = {},
) => [
  "root",
  "Column",
  {
    width: "matchParent",
    height: "matchParent",
    padding: 12,
    borderRadius: 20,
    backgroundColor: "#FFF1F6FE",
    itemMargin: 8,
    ...options,
  },
  children,
];

const wideRoot = (
  children: string[],
  options: Record<string, unknown> = {},
) => [
  "root",
  "Column",
  {
    width: "matchParent",
    height: "matchParent",
    padding: 12,
    borderRadius: 20,
    backgroundColor: "#FFF6F2FF",
    itemMargin: 8,
    ...options,
  },
  children,
];

export const GALLERY_GROUPS: GalleryGroup[] = [
  {
    id: "foundation",
    title: "基础结构",
    description: "Fusion Prompt 允许模型直接组合的布局和基础内容组件。",
  },
  {
    id: "common",
    title: "共享组件",
    description: "组件合同统一定义在 common；实际可用尺寸仍以 2×2 / 2×4 适配规则为准。",
  },
  {
    id: "two-by-two",
    title: "2×2 组件",
    description: "2×2 唯一专属组件：右下锚点动作 CircleButton。",
  },
  {
    id: "two-by-four",
    title: "2×4 组件",
    description: "2×4 专属的整宽明细与固定动作组件。",
  },
];

export const COMPONENT_GALLERY: GalleryComponent[] = [
  {
    id: "row",
    name: "Row",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "横向排列一组同级子组件。",
    usage: "用于同级指标、左右区域或图文组合；子项总宽度与间距必须落在父级预算内。",
    props: ["width", "height", "itemMargin", "justifyContent", "alignItems"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "demo"]),
      ["header", "SingleLineTitle", { title: "Row · 横向排列", fontColor: BLUE }],
      [
        "demo",
        "Row",
        { width: 126, height: 82, itemMargin: 8, alignItems: "center" },
        ["left", "right"],
      ],
      ["left", "Column", { width: 59, height: 82, borderRadius: 14, backgroundColor: WHITE_PANEL, justifyContent: "center", alignItems: "center" }, ["leftText"]],
      ["leftText", "Text", { content: "左", fontSize: 18, fontWeight: 700, fontColor: BLUE }],
      ["right", "Column", { width: 59, height: 82, borderRadius: 14, backgroundColor: WHITE_PANEL, justifyContent: "center", alignItems: "center" }, ["rightText"]],
      ["rightText", "Text", { content: "右", fontSize: 18, fontWeight: 700, fontColor: BLUE }],
    ),
  },
  {
    id: "column",
    name: "Column",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "纵向排列一组有先后层级的子组件。",
    usage: "用于标题、主值、辅助文字等纵向信息流；高度预算按真实子项和间距闭合。",
    props: ["width", "height", "itemMargin", "justifyContent", "alignItems"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "demo"]),
      ["header", "SingleLineTitle", { title: "Column · 纵向排列", fontColor: BLUE }],
      ["demo", "Column", { width: 126, height: 82, padding: 12, itemMargin: 4, borderRadius: 14, backgroundColor: WHITE_PANEL, justifyContent: "center" }, ["primary", "secondary", "caption"]],
      ["primary", "Text", { content: "主信息", fontSize: 18, fontWeight: 700, fontColor: BLUE, maxLines: 1 }],
      ["secondary", "Text", { content: "辅助信息", fontSize: 12, fontWeight: 500, fontColor: BLUE, maxLines: 1 }],
      ["caption", "Text", { content: "补充说明", fontSize: 10, fontWeight: 400, fontColor: "#991F4799", maxLines: 1 }],
    ),
  },
  {
    id: "stack",
    name: "Stack",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "将背景与前景等真实层叠内容放在同一区域。",
    usage: "只用于确有层叠关系的场景，例如图标底板与前景；普通信息排列不使用 Stack。",
    props: ["width", "height", "alignContent", "clip"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "demo"], { alignItems: "center" }),
      ["header", "SingleLineTitle", { title: "Stack · 层叠", fontColor: BLUE }],
      ["demo", "Stack", { width: 82, height: 82, borderRadius: 41, backgroundColor: BLUE_SOFT, alignContent: "center", clip: true }, ["icon", "badge"]],
      ["icon", "Image", { src: "resources/base/media/battery_leaf_fill.svg", width: 36, height: 36, objectFit: "contain", fillColor: BLUE }],
      ["badge", "Text", { content: "68", width: 82, height: 82, fontSize: 12, fontWeight: 700, fontColor: BLUE, textAlign: "center", padding: { top: 54 }, maxLines: 1 }],
    ),
  },
  {
    id: "text",
    name: "Text",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "承载单段可见文字、标签、状态或读数。",
    usage: "必须提供 content；复杂固定结构优先使用对应高阶组件，而不是重复手写多个 Text。",
    props: ["content", "fontSize", "fontWeight", "fontColor", "maxLines"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "content"], { itemMargin: 12 }),
      ["header", "SingleLineTitle", { title: "Text · 文本层级", fontColor: BLUE }],
      ["content", "Column", { width: 126, height: 78, itemMargin: 6, justifyContent: "center" }, ["hero", "body", "caption"]],
      ["hero", "Text", { content: "82 分", fontSize: 24, fontWeight: 700, fontColor: BLUE, maxLines: 1 }],
      ["body", "Text", { content: "今日状态良好", fontSize: 14, fontWeight: 500, fontColor: BLUE, maxLines: 1 }],
      ["caption", "Text", { content: "较昨日提升 6 分", fontSize: 12, fontWeight: 400, fontColor: "#991F4799", maxLines: 1 }],
    ),
  },
  {
    id: "image",
    name: "Image",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "展示一个经过能力候选约束的本地素材。",
    usage: "固定使用语义准确的资源路径；可染色 SVG 显式提供 fillColor，不使用网络图或 emoji。",
    props: ["src", "width", "height", "objectFit", "fillColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "visual"], { alignItems: "center", itemMargin: 14 }),
      ["header", "SingleLineTitle", { title: "Image · 本地素材", fontColor: BLUE }],
      ["visual", "Stack", { width: 76, height: 76, borderRadius: 20, backgroundColor: WHITE_PANEL, alignContent: "center" }, ["icon"]],
      ["icon", "Image", { src: "resources/base/media/phone_fill.svg", width: 40, height: 40, objectFit: "contain", fillColor: BLUE }],
    ),
  },
  {
    id: "divider",
    name: "Divider",
    category: "基础结构",
    sizes: ["2x2", "2x4"],
    summary: "表达内容之间真实存在的分组关系。",
    usage: "仅在同级指标或明确分区之间使用，不作为装饰填空。",
    props: ["width", "height", "vertical", "color"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "metrics"]),
      ["header", "SingleLineTitle", { title: "Divider · 信息分组", fontColor: BLUE }],
      ["metrics", "Row", { width: 126, height: 82, alignItems: "center", justifyContent: "spaceAround" }, ["left", "divider", "right"]],
      ["left", "Text", { content: "68%", width: 54, fontSize: 20, fontWeight: 700, fontColor: BLUE, textAlign: "center" }],
      ["divider", "Divider", { width: 1, height: 54, vertical: true, color: BLUE_SOFT }],
      ["right", "Text", { content: "82%", width: 54, fontSize: 20, fontWeight: 700, fontColor: BLUE, textAlign: "center" }],
    ),
  },
  {
    id: "single-line-title",
    name: "SingleLineTitle",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "单行卡级或分区标题，只承载标题文字。",
    usage: "只承载一个语义分区的单行标题，不使用图标。",
    props: ["title", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "copy"], { itemMargin: 16 }),
      ["header", "SingleLineTitle", { title: "手机电量", fontColor: BLUE }],
      ["copy", "Column", { width: 126, height: 74, justifyContent: "center", itemMargin: 4 }, ["value", "status"]],
      ["value", "Text", { content: "68%", fontSize: 30, fontWeight: 700, fontColor: BLUE, maxLines: 1 }],
      ["status", "Text", { content: "未充电", fontSize: 12, fontWeight: 400, fontColor: "#991F4799", maxLines: 1 }],
    ),
  },
  {
    id: "double-line-title",
    name: "DoubleLineTitle",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "对象标题与紧密相关状态或地点组成的双层标题。",
    usage: "只有两项属于同一对象且标题区域高度足够时使用。",
    props: ["title", "secondaryInfo", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["title", "copy"], { itemMargin: 12 }),
      ["title", "DoubleLineTitle", { title: "阳台传感器", secondaryInfo: "已连接 · 青浦区", fontColor: BLUE }],
      ["copy", "Text", { content: "空气质量良好", fontSize: 18, fontWeight: 700, fontColor: BLUE }],
    ),
  },
  {
    id: "badge",
    name: "Badge",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "标题旁显示同一集合的真实数量。",
    usage: "只能与标题组成标题单元，不能承载状态、百分比或普通核心值。",
    props: ["value", "fontColor", "backgroundColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["titleRow", "copy"], { itemMargin: 18 }),
      ["titleRow", "Row", { width: 126, height: 20, itemMargin: 6, alignItems: "center" }, ["title", "badge"]],
      ["title", "SingleLineTitle", { title: "今日日程", width: 94, fontColor: ORANGE }],
      ["badge", "Badge", { value: 3, fontColor: ORANGE, backgroundColor: ORANGE_SOFT }],
      ["copy", "Text", { content: "下一项 14:30 产品评审", fontSize: 14, fontWeight: 500, fontColor: ORANGE }],
    ),
  },
  {
    id: "emphasized-data",
    name: "EmphasizedData",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "统一表达一个核心值与可选单位。",
    usage: "用于时长、温度、得分等唯一量化主值；不吸收第二指标或辅助说明。",
    props: ["value", "unit?", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "metric"], { justifyContent: "center", alignItems: "center", itemMargin: 18 }),
      ["header", "SingleLineTitle", { title: "睡眠得分", fontColor: PURPLE }],
      ["metric", "EmphasizedData", { value: 82, unit: "分", fontColor: PURPLE }],
    ),
  },
  {
    id: "emphasis-text",
    name: "EmphasisText",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "突出文本结论，并可附一条同语义说明。",
    usage: "用于状态、类别和结论；数值核心、事件和进度保留专用组件。",
    props: ["mainText", "secondaryText?", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "status"], { itemMargin: 18 }),
      ["header", "SingleLineTitle", { title: "耳机状态", fontColor: BLUE }],
      ["status", "EmphasisText", { mainText: "已连接", secondaryText: "FreeBuds Pro 3", fontColor: BLUE }],
    ),
  },
  {
    id: "secondary-body",
    name: "SecondaryBody",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "核心信息后的 2–4 个短补充字段。",
    usage: "不作为分区唯一业务组件；稳定标签—值列表改用 TableText。",
    props: ["items[2..4]", "separator?", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "metric", "detail"], { itemMargin: 8 }),
      ["header", "SingleLineTitle", { title: "昨晚睡眠", fontColor: PURPLE }],
      ["metric", "EmphasizedData", { value: "7小时1分", fontColor: PURPLE }],
      ["detail", "SecondaryBody", { items: [{ label: "深睡 ", value: "2小时15分" }, { label: "午睡 ", value: "0分" }], fontColor: PURPLE }],
    ),
  },
  {
    id: "progress-circle",
    name: "ProgressCircle",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "环心图标与环外读数组成的真实占比组件。",
    usage: "只用于 0–100 的真实占比或有界进度；externalText 同时驱动圆环和读数。",
    props: ["externalText", "icon", "accessibility", "width", "height", "颜色组"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "ratio"], { alignItems: "center" }),
      ["header", "SingleLineTitle", { title: "手机电量", fontColor: BLUE }],
      ["ratio", "ProgressCircle", { externalText: 68, icon: "resources/base/media/battery_leaf_fill.svg", accessibility: { label: "手机电量百分比" }, width: 72, height: 76, fontColor: BLUE, fillColor: "#991F4799", color: BLUE, backgroundColor: BLUE_SOFT }],
    ),
  },
  {
    id: "info-block",
    name: "InfoBlock",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "固定小槽中的主辅信息与可选图标或占比圆环。",
    usage: "每槽只表达一个完整对象；progressCircle visual 只用于真实 0–100 主值。",
    props: ["primaryText", "secondaryText", "unit?", "visual?", "fontColor", "backgroundColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      ["root", "Column", { width: "matchParent", height: "matchParent", padding: 8, borderRadius: 20, backgroundColor: "#FFF1F6FE", itemMargin: 8 }, ["phone", "earphone"]],
      ["phone", "InfoBlock", { primaryText: 68, unit: "%", secondaryText: "正常电量", fontColor: BLUE, backgroundColor: WHITE_PANEL, visual: { type: "progressCircle", icon: "resources/base/media/phone_fill.svg" }, fillColor: BLUE }],
      ["earphone", "InfoBlock", { primaryText: "耳机盒 90%", secondaryText: "已连接", fontColor: BLUE, backgroundColor: WHITE_PANEL }],
    ),
  },
  {
    id: "table-text",
    name: "TableText",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "同一主题下 2–3 项标签—值明细。",
    usage: "两种尺寸共用；进入能完整容纳 2–3 行的连续内容槽，每行保持单行。",
    props: ["items[2..3]", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "table"]),
      ["header", "SingleLineTitle", { title: "明日健康指数", fontColor: BLUE }],
      ["table", "TableText", { items: [{ label: "紫外线", value: "中等" }, { label: "空气质量", value: "良" }, { label: "感冒指数", value: "低" }], fontColor: BLUE }],
    ),
  },
  {
    id: "h-bar-chart",
    name: "H_BarChart",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "比较 2–3 个对象同一指标的横向柱状图。",
    usage: "label 标识对象，valueUnit 保留真实读数，percent 只决定同尺度柱长。",
    props: ["items[2..3]", "fontColor", "barColor", "trackColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "chart"], { itemMargin: 10 }),
      ["header", "SingleLineTitle", { title: "房间用电", fontColor: BLUE }],
      ["chart", "H_BarChart", { items: [{ label: "客厅", valueUnit: "3.2 千瓦时", percent: 80 }, { label: "书房", valueUnit: "1.8 千瓦时", percent: 45 }], fontColor: BLUE, barColor: BLUE, trackColor: BLUE_SOFT }],
    ),
  },
  {
    id: "numeric-ratio-stack",
    name: "NumericRatioStack",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "三个图标可区分对象的紧凑数值占比。",
    usage: "必须恰好三项；对象由图标准确区分，value 只放数值。",
    props: ["items[3]", "direction?", "fontColor", "fillColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "ratios"], { itemMargin: 16 }),
      ["header", "SingleLineTitle", { title: "存储占用", fontColor: BLUE }],
      ["ratios", "NumericRatioStack", { items: [{ icon: "resources/base/media/externaldrive_fill.svg", value: 82, unit: "%" }, { icon: "resources/base/media/earphone_case_16644.svg", value: 61, unit: "%" }, { icon: "resources/base/media/l_circle_fill.svg", value: 34, unit: "%" }], fontColor: BLUE, fillColor: BLUE }],
    ),
  },
  {
    id: "data-display",
    name: "DataDisplay",
    category: "共享组件",
    sizes: ["2x2"],
    summary: "标签、唯一大值与短支撑文本的三行焦点。",
    usage: "合同定义在共享组件中；Fusion 当前只进入 2×2 S-center，不吸收动作或第二指标。",
    props: ["label", "value", "supportingText", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["display"], { justifyContent: "center", alignItems: "center" }),
      ["display", "DataDisplay", { label: "距离发布会", value: 18, supportingText: "天", fontColor: BLUE }],
    ),
  },
  {
    id: "event-card",
    name: "EventCard",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "时间线承载 1–2 个按时间排列的事件。",
    usage: "两项必须放在同一实例中；容量紧张时使用 compact。",
    props: ["items[1..2]", "density?", "fontColor"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "event"], { itemMargin: 8, backgroundColor: "#FFFFF7F2" }),
      ["header", "SingleLineTitle", { title: "下一场会议", fontColor: ORANGE }],
      ["event", "EventCard", { items: [{ title: "产品评审会议", time: "今天 14:30", location: "A3 会议室" }], fontColor: ORANGE }],
    ),
  },
  {
    id: "pill-button",
    name: "PillButton",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "带文字、可选图标的胶囊动作。",
    usage: "一个实例只绑定一个真实动作；2×2 用于底部 CTA，2×4 用于完整内容区直属动作。",
    props: ["label", "onClick", "actionInk", "actionSurface", "icon?", "width?"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "copy", "action"], { itemMargin: 8 }),
      ["header", "SingleLineTitle", { title: "快捷操作", fontColor: BLUE }],
      ["copy", "Text", { content: "保持可见动作名称", width: 126, height: 48, fontSize: 14, fontWeight: 500, fontColor: BLUE, maxLines: 2 }],
      ["action", "PillButton", { label: "查看详情", icon: "resources/base/media/phone_fill.svg", actionSurface: BLUE_SOFT, actionInk: BLUE, fontSize: 14, fontWeight: 500, onClick: action("details") }],
    ),
  },
  {
    id: "circle-button",
    name: "CircleButton",
    category: "2×2 组件",
    sizes: ["2x2"],
    summary: "进入右下锚点槽的纯图标动作。",
    usage: "只在文字按钮无法与必要内容共同容纳时使用，必须提供完整无障碍动作名称。",
    props: ["icon", "accessibility", "onClick", "actionInk", "actionSurface"],
    size: "2x2",
    width: 150,
    height: 150,
    source: dsl(
      squareRoot(["header", "body", "actionRow"], { itemMargin: 4 }),
      ["header", "SingleLineTitle", { title: "蓝牙设备", fontColor: BLUE }],
      ["body", "Text", { content: "FreeBuds 已连接", width: 126, height: 46, fontSize: 16, fontWeight: 700, fontColor: BLUE, maxLines: 2 }],
      ["actionRow", "Row", { width: 126, height: 40, justifyContent: "end", alignItems: "center" }, ["slot"]],
      ["slot", "Stack", { width: 40, height: 40, alignContent: "center" }, ["action"]],
      ["action", "CircleButton", { icon: "resources/base/media/ic_Bluetooth.svg", accessibility: { label: "打开蓝牙设置" }, actionSurface: BLUE_SOFT, actionInk: BLUE, onClick: action("bluetooth") }],
    ),
  },
  {
    id: "progress-line-2",
    name: "ProgressLine2",
    category: "共享组件",
    sizes: ["2x4"],
    summary: "可见读数与真实线性进度的固定组合。",
    usage: "当前值必须相对明确总量，value 与 displayValue 表达同一对象的同一指标。",
    props: ["value", "total", "displayValue", "unit?", "颜色组"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "progress"], { itemMargin: 16 }),
      ["header", "SingleLineTitle", { title: "睡眠恢复度", fontColor: PURPLE }],
      ["progress", "ProgressLine2", { value: 82, total: 100, displayValue: 82, unit: "分", fontColor: PURPLE, color: PURPLE, backgroundColor: PURPLE_SOFT }],
    ),
  },
  {
    id: "text-block",
    name: "TextBlock",
    category: "2×4 组件",
    sizes: ["2x4"],
    summary: "2–4 个等宽同级详情背板。",
    usage: "每项只包含标签和值，进入 W-top-bottom 的详情槽。",
    props: ["items[2..4]", "fontColor", "backgroundColor"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "details"], { itemMargin: 16 }),
      ["header", "SingleLineTitle", { title: "睡眠详情", fontColor: PURPLE }],
      ["details", "TextBlock", { items: [{ label: "睡眠时长", value: "7小时1分" }, { label: "深睡时长", value: "2小时15分" }, { label: "清醒次数", value: "2次" }], fontColor: PURPLE, backgroundColor: WHITE_PANEL }],
    ),
  },
  {
    id: "card-button",
    name: "CardButton",
    category: "2×4 组件",
    sizes: ["2x4"],
    summary: "固定动作槽中的文字动作与可选视觉位。",
    usage: "用于 132 × 57vp 固定动作槽，一个实例只绑定一个真实动作。",
    props: ["label", "onClick", "fontColor", "backgroundColor", "icon?"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "actions"], { itemMargin: 16, backgroundColor: "#FFFFF7F2" }),
      ["header", "SingleLineTitle", { title: "快捷操作", fontColor: ORANGE }],
      ["actions", "Row", { width: 276, height: 57, itemMargin: 12 }, ["calendar", "focus"]],
      ["calendar", "CardButton", { label: "查看日程", icon: "resources/base/media/calendar_fill.svg", fillColor: ORANGE, fontColor: ORANGE, backgroundColor: WHITE_PANEL, onClick: action("calendar") }],
      ["focus", "CardButton", { label: "专注模式", fontColor: ORANGE, backgroundColor: WHITE_PANEL, onClick: action("focus") }],
    ),
  },
  {
    id: "progress-circle-single",
    name: "ProgressCircleSingle",
    category: "共享组件",
    sizes: ["2x2", "2x4"],
    summary: "单环与右侧标签、读数、状态说明。",
    usage: "两种尺寸共用；2×2 使用普通规格，2×4 使用 compact 规格，只表达单个真实比例及同对象说明。",
    props: ["value", "total", "icon", "displayValue", "label", "secondaryLabel?", "颜色组"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "progress"], { alignItems: "center", itemMargin: 18, backgroundColor: "#FFF1F6FE" }),
      ["header", "SingleLineTitle", { title: "手机电量", fontColor: BLUE }],
      ["progress", "ProgressCircleSingle", { value: 68, total: 100, icon: "resources/base/media/battery_leaf_fill.svg", displayValue: "68%", label: "手机电量", secondaryLabel: "未充电", fontColor: BLUE, color: BLUE, backgroundColor: BLUE_SOFT }],
    ),
  },
  {
    id: "top-text-bottom-value",
    name: "TopTextBottomValue",
    category: "2×4 组件",
    sizes: ["2x4"],
    summary: "三组同级标签、数值和单位。",
    usage: "恰好三个等权指标，由组件确定列宽、分隔线和统一对齐。",
    props: ["items[3]", "fontColor", "dividerColor"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "metrics"], { itemMargin: 14 }),
      ["header", "SingleLineTitle", { title: "我的健康数据", fontColor: PURPLE }],
      ["metrics", "TopTextBottomValue", { items: [{ label: "睡眠得分", value: 80, unit: "分" }, { label: "消耗热量", value: 92, unit: "千卡" }, { label: "今日步数", value: 2031, unit: "步" }], fontColor: PURPLE, dividerColor: PURPLE_SOFT }],
    ),
  },
  {
    id: "summary-list",
    name: "SummaryList",
    category: "共享组件",
    sizes: ["2x4"],
    summary: "2–3 条等权、单行的短摘要列表。",
    usage: "合同定义在共享组件中；Fusion 当前只进入 2×4 的列表明细槽，每项固定单行显示。",
    props: ["items[2..3]", "fontColor", "backgroundColor"],
    size: "2x4",
    width: 300,
    height: 150,
    source: dsl(
      wideRoot(["header", "list"], { itemMargin: 4, backgroundColor: "#FFFFF7F2" }),
      ["header", "SingleLineTitle", { title: "近期日程", fontColor: ORANGE }],
      ["list", "SummaryList", { items: ["项目阶段性汇报", "确认 Q3 设计需求", "申请下周出差"], fontColor: ORANGE, backgroundColor: WHITE_PANEL }],
    ),
  },
];

export const FUSION_COMPONENT_NAMES = [
  "Row",
  "Column",
  "Stack",
  "Text",
  "Image",
  "Divider",
  "SingleLineTitle",
  "DoubleLineTitle",
  "Badge",
  "EmphasizedData",
  "EmphasisText",
  "SecondaryBody",
  "ProgressCircle",
  "InfoBlock",
  "TableText",
  "H_BarChart",
  "NumericRatioStack",
  "DataDisplay",
  "EventCard",
  "PillButton",
  "CircleButton",
  "ProgressLine2",
  "TextBlock",
  "CardButton",
  "ProgressCircleSingle",
  "TopTextBottomValue",
  "SummaryList",
] as const;
